version: 1.0.{build}
skip_tags: true
image: Visual Studio 2019
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  project: DIPSCrewPlanner.sln
  verbosity: minimal
before_build:
  - nuget restore
  - ps: "$env:ApplicationVersion=$env:APPVEYOR_BUILD_VERSION"
after_build:
  - ps: $root = Resolve-Path .\bin\Release\app.publish;
    [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName releaseBuild }